"
"	Phil's (@mrphilh) .vimrc file.
"
"	Various config settings stolen with love from:
"	- https://github.com/nvie/vimrc
"

filetype off


" enable pathogen
execute pathogen#infect()
call pathogen#helptags()

" don't sacrifice functionality and features just to preserve backward compatibility with vi
set nocompatible

" turn on syntax highlighting
syntax on
set background=dark
colorscheme vividchalk

" Fish shell is not POSIX complaint
set shell=bash

" if a given file type (perl, ruby, python, c, etc) has its own special auto-indentation rules, use them
filetype plugin indent on

" Editing behaviour {{{
set showmode                    " always show what mode we're currently editing in
set nowrap                      " don't wrap lines
set tabstop=4                   " a tab is four spaces
set softtabstop=4               " when hitting <BS>, pretend like a tab is removed, even if spaces
set expandtab                   " expand tabs by default (overloadable per file type later)
set shiftwidth=4                " number of spaces to use for autoindenting
set shiftround                  " use multiple of shiftwidth when indenting with '<' and '>'
set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set autoindent                  " always set autoindenting on
set copyindent                  " copy the previous indentation on autoindenting
set number                      " always show line numbers
set showmatch                   " set show matching parenthesis
set ignorecase                  " ignore case when searching
set smartcase                   " ignore case if search pattern is all lowercase,
				                "    case-sensitive otherwise
set smarttab                    " insert tabs on the start of a line according to
                				"    shiftwidth, not tabstop
set scrolloff=4                 " keep 4 lines off the edges of the screen when scrolling
set virtualedit=all             " allow the cursor to go in to "invalid" places
set hlsearch                    " highlight search terms
set incsearch                   " show search matches as you type
set gdefault                    " search/replace "globally" (on a line) by default

set list
set listchars=tab:▸\ ,trail:·,extends:#,nbsp:·

"set nolist                      " don't show invisible characters by default,
                				" but it is enabled for some file types (see
			                    "   later)
set pastetoggle=<F2>            " when in insert mode, press <F2> to go to
                				"    paste mode, where you can paste mass data
			                    "    that won't be autoindented
set mouse=a                     " enable using the mouse if terminal emulator
                				"    supports it (xterm does)
set fileformats="unix,dos,mac"
set formatoptions+=1            " When wrapping paragraphs, don't end lines
                				"    with 1-letter words (looks stupid)


set nrformats=                  " make <C-a> and <C-x> play well with
                				"    zero-padded numbers (i.e. don't consider
                				"    them octal or hex)
set shortmess+=I                " hide the launch screen
set clipboard=unnamed           " normal OS clipboard interaction

"Basic vim ninja training
noremap <up> <nop>
noremap <down> <nop>
noremap <left> <nop>
noremap <right> <nop>

"Remap tasklist so it does not interfere with command-t
map <leader>v <Plug>TaskList

autocmd BufWritePre * :%s/\s\+$//e      "Remove trailing whitespace on save

"Mark when I've gone over 80 character line lenght
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%81v.*/

" Status Line config
set laststatus=2
"set statusline=
set statusline+=%7*\[%n]                                  "buffernr
set statusline+=%1*\ %<%F\                                "File+path
set statusline+=%2*\ %y\                                  "FileType
set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
set statusline+=%4*\ %{&ff}\                              "FileFormat (dos/unix..)
set statusline+=%5*\ %{&spelllang}\%{HighlightSearch()}\  "Spellanguage & Highlight on?
set statusline+=%8*\ %=\ row:%l/%L\ (%03p%%)\             "Rownumber/total (%)
set statusline+=%9*\ col:%03c\                            "Colnr
set statusline+=%0*\ \ %m%r%w\ %P\ \                      "Modified? Readonly? Top/bot.

function! HighlightSearch()
  if &hls
    return 'H'
  else
    return ''
  endif
endfunction

"hi User1 ctermfg=#ffdad8  ctermbg=#880c0e
"hi User2 ctermfg=#000000  ctermbg=#F4905C
"hi User3 ctermfg=#292b00  ctermbg=#f4f597
"hi User4 ctermfg=#112605  ctermbg=#aefe7B
"hi User5 ctermfg=#051d00  ctermbg=#7dcc7d
"hi User7 ctermfg=#ffffff  ctermbg=#880c0e gui=bold
"hi User8 ctermfg=#ffffff  ctermbg=#5b7fbb
"hi User9 ctermfg=#ffffff  ctermbg=#810085
"hi User0 ctermfg=#ffffff  ctermbg=#094afe
