"
"	Phil's (@mrphilh) .vimrc file.
"
"	Various config settings stolen with love from:
"	- https://github.com/nvie/vimrc
"

filetype off

let os = substitute(system('uname'), '\n', '', '')
if os == 'Darwin' || os == 'Mac'
    let s:OS = 'osx'
endif

" enable pathogen
execute pathogen#infect()
call pathogen#helptags()

" don't sacrifice functionality and features just to preserve backward compatibility with vi
set nocompatible

" turn on syntax highlighting
syntax on
set background=dark
colorscheme getafe

" Fish shell is not POSIX complaint
set shell=bash

" if a given file type (perl, ruby, python, c, etc) has its own special auto-indentation rules, use them
filetype plugin indent on

" Editing behaviour {{{
set showmode                    " always show what mode we're currently editing in
set nowrap                      " don't wrap lines
set tabstop=4                   " a tab is four spaces
set softtabstop=4               " when hitting <BS>, pretend like a tab is removed, even if spaces
set expandtab                   " expand tabs by default (overloadable per file type later)
set shiftwidth=4                " number of spaces to use for autoindenting
set shiftround                  " use multiple of shiftwidth when indenting with '<' and '>'
set backspace=indent,eol,start  " allow backspacing over everything in insert mode
set autoindent                  " always set autoindenting on
set copyindent                  " copy the previous indentation on autoindenting
set number                      " always show line numbers
set showmatch                   " set show matching parenthesis
set ignorecase                  " ignore case when searching
set smartcase                   " ignore case if search pattern is all lowercase,
				                "    case-sensitive otherwise
set smarttab                    " insert tabs on the start of a line according to
                				"    shiftwidth, not tabstop
set scrolloff=4                 " keep 4 lines off the edges of the screen when scrolling
set virtualedit=all             " allow the cursor to go in to "invalid" places
set hlsearch                    " highlight search terms
set incsearch                   " show search matches as you type
set gdefault                    " search/replace "globally" (on a line) by default

set list
set listchars=tab:▸\ ,trail:·,extends:#,nbsp:·,eol:¬

"set nolist                      " don't show invisible characters by default,
                				" but it is enabled for some file types (see
			                    "   later)
set pastetoggle=<F2>            " when in insert mode, press <F2> to go to
                				"    paste mode, where you can paste mass data
			                    "    that won't be autoindented
set mouse=v                     " enable using the mouse if terminal emulator
                				"    supports it (xterm does)
set fileformats="unix,dos,mac"
set formatoptions+=1            " When wrapping paragraphs, don't end lines
                				"    with 1-letter words (looks stupid)


set nrformats=                  " make <C-a> and <C-x> play well with
                				"    zero-padded numbers (i.e. don't consider
                				"    them octal or hex)
set shortmess+=I                " hide the launch screen
set clipboard=unnamed           " normal OS clipboard interaction

" Command-T variables
let g:CommandTFileScanner="find"
let g:CommandTMaxFiles=100000
let g:CommandTMaxCacheDirectories=50
set wildignore+=**/.git/*,.DS_Store,**/*.pyc,**/Cloud.build/*,*.obj,*.o
"Basic vim ninja training
"noremap <up> <nop>
"noremap <down> <nop>
"noremap <left> <nop>
"noremap <right> <nop>

"Remap window commands
nmap <leader>s :split<CR>
nmap <leader>vs :vsplit<CR>
"Buffer commands
"Create a new buffer
nmap <leader>T :enew<CR>
" Move to the next buffer
nmap <leader>l :bnext<CR>
" Move to the previous buffer
nmap <leader>h :bprevious<CR>
" Close the current buffer and move to the previous one
" This replicates the idea of closing a tab
nmap <leader>bq :bp <BAR> bd #<CR>
" Show all open buffers and their status
nmap <leader>bl :ls<CR>

" Remap :tselect for easier tag jumping
nmap <leader>] :tselect<CR>
" Make it easier to close a buffer and keep a split
nmap <leader>q :BD<CR>
"
"Remap tasklist so it does not interfere with command-t
map <leader>v <Plug>TaskList

"autocmd BufWritePre * :%s/\s\+$//e      "Remove trailing whitespace on save

"Mark when I've gone over 100 character line lenght
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%101v.*/

" Status Line config
set laststatus=2
"set statusline=
set statusline+=%7*\[%n]                                  "buffernr
set statusline+=%1*\ %<%F\                                "File+path
set statusline+=%2*\ %y\                                  "FileType
set statusline+=%3*\ %{''.(&fenc!=''?&fenc:&enc).''}      "Encoding
set statusline+=%3*\ %{(&bomb?\",BOM\":\"\")}\            "Encoding2
set statusline+=%4*\ %{&ff}\                              "FileFormat (dos/unix..)
set statusline+=%5*\ %{&spelllang}\%{HighlightSearch()}\  "Spellanguage & Highlight on?
set statusline+=%8*\ %=\ row:%l/%L\ (%03p%%)\             "Rownumber/total (%)
set statusline+=%9*\ col:%03c\                            "Colnr
set statusline+=%0*\ \ %m%r%w\ %P\ \                      "Modified? Readonly? Top/bot.

" CSCOPE Confings
    "Below is the minimum key mappings.
"nnoremap <leader>fa :call cscope#findInteractive(expand('<cword>'))<CR>
"nnoremap <leader>l :call ToggleLocationList()<CR>

    "Some optional key mappings to search directly.

" s: Find this C symbol
"nnoremap  <leader>fs :call cscope#find('s', expand('<cword>'))<CR>
" g: Find this definition
"nnoremap  <leader>fg :call cscope#find('g', expand('<cword>'))<CR>
" d: Find functions called by this function
"nnoremap  <leader>fd :call cscope#find('d', expand('<cword>'))<CR>
" c: Find functions calling this function
"nnoremap  <leader>fc :call cscope#find('c', expand('<cword>'))<CR>
" t: Find this text string
"nnoremap  <leader>ft :call cscope#find('t', expand('<cword>'))<CR>
"" e: Find this egrep pattern
"nnoremap  <leader>fe :call cscope#find('e', expand('<cword>'))<CR>
" f: Find this file
"nnoremap  <leader>ff :call cscope#find('f', expand('<cword>'))<CR>
" i: Find files #including this file
"nnoremap  <leader>fi :call cscope#find('i', expand('<cword>'))<CR>

" Airline Config

if has('gui_running')
    " Who uses a GUI in GVim anyways? Let's be serious.
    set guioptions=aegirLt

    " Let's make the fonts look nice
    if s:OS == 'osx'
        set guifont=Droid\ Sans\ Mono\ for\ Powerline:h11
    elseif s:OS == 'linux'
        set guifont=DejaVu\ Sans\ Mono\ for\ Powerline\ 9
    endif
endif

let g:airline_theme="powerlineish"

" Enable Powerline fonts
let g:airline_powerline_fonts = 1

" Fix Broken symbols
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"

" Enable buffer list across the top
let g:airline#extensions#tabline#enabled = 1

" Show just the filename
let g:airline#extensions#tabline#fnamemod = ':t'

function! HighlightSearch()
  if &hls
    return 'H'
  else
    return ''
  endif
endfunction
"Relative number switching.
function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc

nnoremap <C-n> :call NumberToggle()<cr>  
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

"hi User1 ctermfg=#ffdad8  ctermbg=#880c0e
"hi User2 ctermfg=#000000  ctermbg=#F4905C
"hi User3 ctermfg=#292b00  ctermbg=#f4f597
"hi User4 ctermfg=#112605  ctermbg=#aefe7B
"hi User5 ctermfg=#051d00  ctermbg=#7dcc7d
"hi User7 ctermfg=#ffffff  ctermbg=#880c0e gui=bold
"hi User8 ctermfg=#ffffff  ctermbg=#5b7fbb
"hi User9 ctermfg=#ffffff  ctermbg=#810085
"hi User0 ctermfg=#ffffff  ctermbg=#094afe
